"""Add case_id to observations table

Revision ID: ca948f1fcd1f
Revises: cad15b88db24
Create Date: 2025-11-25 19:35:12.215732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca948f1fcd1f'
down_revision: Union[str, Sequence[str], None] = 'cad15b88db24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('observations', sa.Column('case_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('observations', 'case_id')
    # ### end Alembic commands ###
