"""Add task_id to observations table

Revision ID: 82dfdfb330e1
Revises: ca948f1fcd1f
Create Date: 2025-11-25 21:16:00.622416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82dfdfb330e1'
down_revision: Union[str, Sequence[str], None] = 'ca948f1fcd1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('observations', sa.Column('task_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('observations', 'task_id')
    # ### end Alembic commands ###
