"""Change committed_by to string in collaboration_requests

Revision ID: cad15b88db24
Revises: 2185315ff7a4
Create Date: 2025-11-23 17:34:09.724066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cad15b88db24'
down_revision: Union[str, Sequence[str], None] = '2185315ff7a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Primero eliminar la foreign key
    op.drop_constraint('collaboration_requests_committed_by_fkey', 'collaboration_requests', type_='foreignkey')
    # Luego cambiar el tipo de columna
    op.alter_column('collaboration_requests', 'committed_by',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Primero cambiar el tipo de columna de vuelta
    op.alter_column('collaboration_requests', 'committed_by',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # Luego recrear la foreign key
    op.create_foreign_key('collaboration_requests_committed_by_fkey', 'collaboration_requests', 'users', ['committed_by'], ['id'])
    # ### end Alembic commands ###
