"""make_committed_by_not_null

Revision ID: 5ae701122239
Revises: f41ffd43acbb
Create Date: 2025-10-24 15:02:10.156278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ae701122239'
down_revision: Union[str, Sequence[str], None] = 'f41ffd43acbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('collaboration_requests', 'committed_by',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('collaboration_requests', 'committed_by',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
