"""DAdd collaboration requests table

Revision ID: 83bd1a87395a
Revises: 3af6f6ee13e6
Create Date: 2025-10-23 21:25:16.691343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83bd1a87395a'
down_revision: Union[str, Sequence[str], None] = '3af6f6ee13e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collaboration_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_plan_stage_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('requested_amount', sa.Float(), nullable=True),
    sa.Column('amount_currency', sa.String(), nullable=True),
    sa.Column('requested_date', sa.DateTime(), nullable=True),
    sa.Column('is_committed', sa.Boolean(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('committed_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['work_plan_stage_id'], ['work_plan_stages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collaboration_requests_id'), 'collaboration_requests', ['id'], unique=False)
    op.create_index(op.f('ix_work_plan_stages_id'), 'work_plan_stages', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_work_plan_stages_id'), table_name='work_plan_stages')
    op.drop_index(op.f('ix_collaboration_requests_id'), table_name='collaboration_requests')
    op.drop_table('collaboration_requests')
    # ### end Alembic commands ###
