"""update_committed_by_to_fk

Revision ID: f41ffd43acbb
Revises: 83bd1a87395a
Create Date: 2025-10-24 14:54:20.138865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f41ffd43acbb'
down_revision: Union[str, Sequence[str], None] = '83bd1a87395a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # First, set any non-NULL string values to NULL (since we can't convert strings to integers)
    op.execute("UPDATE collaboration_requests SET committed_by = NULL WHERE committed_by IS NOT NULL")
    
    # Then alter the column type using USING clause
    op.execute("ALTER TABLE collaboration_requests ALTER COLUMN committed_by TYPE INTEGER USING committed_by::integer")
    
    # Finally, create the foreign key
    op.create_foreign_key(None, 'collaboration_requests', 'users', ['committed_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'collaboration_requests', type_='foreignkey')
    op.alter_column('collaboration_requests', 'committed_by',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
